# Change these first
owner: rcy1314 # Your GitHub organization or username, where this repository lives
repo: runtime # The name of this repository

sites:
  - name: Noise宝藏阁
    url: https://noisevip.cn
  - name: Noise社区站
    url: https://www.efficiency.vip
  - name: Noise导航站
    url: https://www.noisedh.cn
  - name: 频道推送器
    url: https://www.efficiencynoise.top
  - name: Noise资源库
    url: https://www.noiseyp.top
  - name: Noise知识效率集
    url: https://www.noisesite.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: rcy1314.github.io/runtime/
  baseUrl: /runtime
  logoUrl: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-6).4x3uticipew0.jpg
  name: Noise的站点运行监控
  introTitle: "欢迎你的访问"
  introMessage: 这里是一些站点服务的运行状况
  navbar:
    - title: 运行状况
      href: /
    - title: 主页
      href: https://www.noisework.cn
      
  status-website:
  theme: night
  
  status-website:
  name: Noise的站点运行监控
  logoUrl: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-6).4x3uticipew0.jpg
  
  status-website:
  js: "<script>
<span id="runtime_span"></span>
<script type="text/javascript">function show_runtime(){window.setTimeout("show_runtime()",1000);X=new
Date("18/02/2022 5:22:00");
Y=new Date();T=(Y.getTime()-X.getTime());M=246060*1000;
a=T/M;A=Math.floor(a);b=(a-A)*24;B=Math.floor(b);c=(b-B)*60;C=Math.floor((b-B)*60);D=Math.floor((c-C)*60);
runtime_span.innerHTML="本站勉强运行: "+A+"天"+B+"小时"+C+"分"+D+"秒"}show_runtime();</script>
</center>
 </script>" 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
